name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt install qemu-utils bzip2

      - name: Build
        run: sudo -E ./build-image.sh

      - uses: actions/upload-artifact@v3
        with:
          name: alpine-virt-image.qcow2.bz2
          path: "*.bz2"

      - name: Read version
        id: getversion
        run: echo "version=$(cat version)" >> $GITHUB_OUTPUT

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.bz2"
          tag: ${{ steps.getversion.outputs.version }}

